name: trigger-workflow

run-name: Aprendiendo a manejar diferentes triggers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
      - feature/*
  workflow_dispatch:
    inputs:
      lenguaje_favorito:
        description: '¿Cuál es tu lenguaje de programación favorito?'
        required: true
        type: choice
        default: JavaScript
        options:
          - JavaScript
          - Python
          - Java
          - C#
          - Go
      nombre:
        description: 'Tu nombre'
        required: true
        type: choice
        default: 'Juan Pérez'
        options:
          - 'Juan Pérez'
          - 'María Gómez'
          - 'Pedro López'
          - 'Ana Torres'
          - 'Luis Hernández'

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Saludo
        run: echo "Hola, ${{ github.actor }}!"
      - name: Mostrar lenguaje favorito (solo si es dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Lenguaje favorito: ${{ github.event.inputs.lenguaje_favorito }}"
          echo "Nombre elegido: ${{ github.event.inputs.nombre }}"
  hola-mundo:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.lenguaje_favorito == 'JavaScript' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Mensaje condicional
        run: echo "Solo se ejecuta porque elegiste JavaScript, ${{ github.event.inputs.nombre }}"